### ISSUE TITLE
Subgraphs

### ISSUE THREAD

**Issue by joelrebel** [nikolaydubina/jsonl-graph#17]
Hi! thank you for this project!
I'd like to know if theres a plan for Subgraphs support, if not I would like to give the implementation a try :)

**Comment by nikolaydubina** [comment]
Subgraphs is nice. Do you have some ideas on input API?

If you want to add this,

Before you invest effort to it, could you make Issue or (PR with just description) showing your decision for API input and Graphviz expected outcome? Probably we need couple of options and pick the best one.

Probably this is not too complex, but I have hunch need to watch-out API here..

Thanks!!

**Comment by joelrebel** [comment]
My usecase here is to generate state machine graphs from a state machine defined in Go, 

The graph I indented to render inlcudes a sub-statemachine - I've pasted an example dot file below, where a unique set of nodes can be clustered in subgraphs,

I looked at how this can be implemented and its seems like the `Graph` type would need 
have  a new `Subgraph` type field which is then Renderable.  

The `Subgraph` type would need to be able to reference unique list of Nodes - haven't put further thought into this.

At the moment I may not put further effort into it since other work has taken priority,
but if this set of changes makes sense I can give it a try in my spare time and send in a PR.


```
digraph G {                             
rankdir=TB

subgraph {                                                                        
    cluster=true;                                                                 
    label = "state machine";
    
    "failed";
    "active";                                                                     
    "queued";                                                                    
    "success";                                                                    
}                                                                                 

subgraph  {                                                                       
    cluster=true;                                                                 
    label = "sub-statmachine";                                          
    "1";                                                     
    "2";                                                            
    "3";                                                            
    "4";                                                           
}                                                                                 

    "1" -> "2"
    "1" -> "failed"
    "2" -> "3"
    "2" -> "failed"
    "3" -> "4"
    "3" -> "failed"
    "4" -> "success"
    "4" -> "failed"
    
    "queued" -> "active"
    "active" -> "1"
    "active" -> "success"
}           
```

**Comment by nikolaydubina** [comment]
Got it! Make sense.

Back to API, how would you propose to pass this data to this tool?

Key API design for this tool is JSONL. So it should be able to concat multiple JSONL files and still get a valid graph.

So one option I see is to pass through fields in nodes:
```json
{"id": "node-a", "subgraph": "sub-graph-A"}
```

Would like to hear if this works for you. Likely you are generating this in `jq`, right? Can you set subgraph like this?

Cheers!

**Comment by joelrebel** [comment]
Thanks for your reply,

Yep if each node had a subgraph field that would work for my use case as well. 

In my case I'm not using `jq`, the code defines the nodes and edges and renders it through the methods you have exposed in this tool,


```go
import (
 "github.com/nikolaydubina/jsonl-graph/dot"
 "github.com/nikolaydubina/jsonl-graph/graph"
 )

m, err := sm.NewStateMachine()
if err != nil {
  log.Fatal(err)
}

// state machine object to be graphed
statemachine := m.Describe()

g := graph.NewGraph()
for _, tnode := range statemachine.Nodes {
  g.AddNode(graph.NodeData{tnode.ID: tnode.Description})
}

for _, tedge := range statemachine.Edges {
  g.AddEdge(graph.EdgeData{"from": tedge.From, "to": tedge.To, "label": tedge.Name})
}

dotg := dot.NewBasicGraph(g, dot.TB)

fmt.Println(dotg.Render())
```

**Comment by nikolaydubina** [comment]
Got it!

This tool is focuses on converting JSONL to Graphviz. So if you already
accessing it in Go, might as well write output in Dot format directly. Dot
format is fairly straightforward. This will remove one more dependency and
give you freedom and control to write output exactly  for your usecase.

Probably there are dedicated packages for writing Dot files from Go. If
none, can create one! 😁

As for rendering, I was working on native Go graph rendering. But it is
very hard task. So recommend to either invoke C calls to graphviz through
cgo or via external process call to graphiviz.

As for this tool, lets focus in this tool on CLI and JSONL. So API of JSONL
and STDIN/STDOUT is important.

That being said, subgraphs is nice to have. I myself wanted to add them. So
likely will add in future if nobody else adds!

-- Nikolay

**Comment by joelrebel** [comment]
Thanks again for your input! I see theres other libraries that I can use for my usecase, I'll give them a try :)
